name: ReSIDE
channels:
  - pytorch
  - defaults
dependencies:
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - cffi=1.13.2
  - colorama=0.4.3
  - cudatoolkit=10.1.243
  - cycler=0.10.0
  - decorator=4.4.1
  - defusedxml=0.6.0
  - entrypoints=0.3
  - freetype=2.9.1
  - h5py=2.9.0
  - hdf5=1.10.4
  - icu=58.2
  - importlib_metadata=1.3.0
  - intel-openmp=2019.4
  - ipykernel=5.1.3
  - ipython=7.11.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.15.2
  - jinja2=2.10.3
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=5.3.4
  - jupyter_console=6.0.0
  - jupyter_core=4.6.1
  - kiwisolver=1.1.0
  - libpng=1.6.37
  - libsodium=1.0.16
  - libtiff=4.1.0
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - more-itertools=8.0.2
  - nbconvert=5.6.1
  - nbformat=4.4.0
  - ninja=1.9.0
  - notebook=6.0.2
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.1.1d
  - pandas=1.0.1
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.5.2
  - pickleshare=0.7.5
  - pillow=6.2.2
  - pip=19.3.1
  - plac=1.1.0
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.10
  - pycparser=2.19
  - pygments=2.5.2
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - pyrsistent=0.15.6
  - python=3.7.6
  - python-dateutil=2.8.1
  - pytorch=1.3.1
  - pytz=2019.3
  - pyzmq=18.1.0
  - qt=5.9.7
  - qtconsole=4.6.0
  - scipy=1.4.1
  - send2trash=1.5.0
  - setuptools=44.0.0
  - sip=4.19.8
  - six=1.13.0
  - sqlite=3.30.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - torchvision=0.4.2
  - tornado=6.0.3
  - traitlets=4.3.3
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - xz=5.2.4
  - zeromq=4.3.1
  - zipp=0.6.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
      - chardet==3.0.4
      - click==7.1.2
      - configparser==5.0.0
      - docker-pycreds==0.4.0
      - efficientnet-pytorch==0.6.3
      - gitdb==4.0.4
      - gitpython==3.1.1
      - gql==0.2.0
      - graphql-core==1.1
      - idna==2.9
      - nvidia-ml-py3==7.352.0
      - pathtools==0.1.2
      - promise==2.3
      - psutil==5.7.0
      - pyyaml==5.3.1
      - requests==2.23.0
      - sentry-sdk==0.14.3
      - shortuuid==1.0.1
      - smmap==3.0.2
      - subprocess32==3.5.4
      - urllib3==1.25.9
      - wandb==0.8.34
      - watchdog==0.10.2
